server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERIVCE
                fallbackuri: forward:/api/userServiceFallBack
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/api/departments/**
          filters:
            - name: CircuitBreaker
              args:
                name: DEPARTMENT-SERIVCE
                fallbackuri: forward:/api/departmentServiceFallBack

hystrix:
  command:
    fallbackcmd:
      execution:
        ioslation:
          thread:
            timeoutInMilliseconds: 4000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
