server:
  port: 9083
  # default
  servlet:
    context-path: /

spring:
  # Config mail sender
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: tranglong434@gmail.com
    password: sautzukpgqalmqqi
    port: 587
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

## swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html

##level. có dấu '.' để không bị error run program
logging:
  level. : debug
