server:
  port: 9003
  # default
  servlet:
    context-path: /

spring:
  # Config mail sender
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: tranglong434@gmail.com
    password: sautzukpgqalmqqi
    port: 587
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: NOTIFICATION-SERIVCE
  zipkin:
    base-url: http://127.0.0.1:9411/

## swagger-ui custom path
springdoc:
  swagger-ui:
    path: swagger-ui.html
